### ISSUE TITLE
Clean up the About Us sections

### ISSUE THREAD

**Issue by ney927** [Carleton-Blueprint/technolgap#26]
### Pretext -**please read before starting task**
- don't worry about issues with the homepage section as Divya is working on that
- the homepage component in src/components uses a lot of media queries which would be a good reference if you are unfamiliar 
- make sure you read the _entirety_ of a task (i.e. a text box) before starting it

### Tasks

- [ ]  add ribbons and sparkles to the About Us Pages

- [x] add pink text to the About Us subtitle
    -  ![image](https://github.com/user-attachments/assets/307a042d-8c69-4050-bb40-f5b10b37cf97)

- [ ] create a smooth transition between the background gradients of the about us sections
    - currently there is an obvious line in between and then gradient is not correct between the Core Values and Milestone
    - ![image](https://github.com/user-attachments/assets/64c2255c-9087-4b43-9149-818a58102e65)
    - feel free to completely change how the background is implemented.
    - honestly i would **_heavily recommend_** using the background images found [here](https://drive.google.com/drive/folders/1rzPukZH66c0jNJYjzSImK-2qvYCSLltT?usp=drive_link) because it will be easy to update the site if Arabella decides to change the backgrounds (which I think she is actually doing right now....)
    
- [ ] ensure the pages (especially the ribbon/sparkle placement) look good responsively 
    - with allowance for errors for mobile screen size as the official designs have not come out
    
- [ ] fix the milestone circles to be more accurate to the design
    - [design](https://www.figma.com/design/cUxhBXDDa5WpdDQryf8FNo/Technolgap-Desktop)
    - features (that I can identify- feel free to develop your own list):
        - higher placement on the text in the circle
        - more padding on the text so it doesn't touch edges of the circle
        - white border and small shadow at the bottom of the circle
        - individual circles do not have gradients -> rather it is the shade of green that lightens with each milestone
            - suggestion: create an increment variable using the total number of milestones (ex: 255 / total) and use that increment to calculate the rgb value of the green background colour
            - ^^if this suggestion is confusing reach out to me. overall this isn't a large detail so if you are struggling don't spend too much time on it
        - overall make the circle larger (try and maintain the ratio of circle radius to screen size by adding media queries to scale the component
            - ex: ![image](https://github.com/user-attachments/assets/4f4a734d-e64f-4bf1-bdfe-3aa5f13c20ff)

- [ ] resolve any Astro Audit errors that the page might have
    - ![image](https://github.com/user-attachments/assets/eac3b617-58d5-45a8-856c-187c94bbedfa)

- [ ] look for any other issues on the page (check at different screen sizes) and compare the site to the [figma design](https://www.figma.com/design/cUxhBXDDa5WpdDQryf8FNo/Technolgap-Desktop)
