### ISSUE TITLE
Polish up Navbar

### ISSUE THREAD

**Issue by ney927** [Carleton-Blueprint/technolgap#27]
### Tasks
- [x] make the mobile navbar active after a certain screen size
    - after I merged the branches I noticed that functionality was not working anymore even though I accepted all of your changes
    - you can reference the original code from your branch [here](https://github.com/Carleton-Blueprint/technolgap/tree/Desktop-Mobile-Navbar) to help figure this out
    - I am sorry I wasn't able to merge it smoothly, but I figured since you built it you would be the best choice to debug it. hopefully it is not a big issue 😬 

- [x] fix logo positioning
    - check page responsively
    - ensure that the logo is always on the left hand corner and an appropriate size

- [x] make the background colour opaque rather than transparent

- [x] add a dropdown for the About Us tab that contains (and redirects to) 
    - Core Values, Milestones, Our Team (although this page doesn't exist yet so just direct to # or /coming-soon)
    
- [ ] any other changes you feel are necessary
